name: deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Build and publish to GitHub pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    concurrency:
      group: "pages"
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Wheel Builder Dependencies
        run: pip install wheel setuptools

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install protoc compiler
        run: |
          sudo apt-get update
          sudo apt-get install protobuf-compiler

      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.18.0

      - name: Build bundle
        run: |
          # 1. Create an absolute path for dist
          export DIST_PATH=$(pwd)/dist
          rm -rf $DIST_PATH
          
          # 2. Build Zola site
          (cd www-zola && zola build --output-dir $DIST_PATH)

          # 3. Build Rust WASM
          wasm-pack build --release --target web
          cp -r pkg $DIST_PATH/

          # 4. Build Construct 2.8.8
          mkdir -p temp_build
          cd temp_build
          wget https://files.pythonhosted.org/packages/b6/2c/66bab4fef920ef8caa3e180ea601475b2cbbe196255b18f1c58215940607/construct-2.8.8.tar.gz
          tar xzf construct-2.8.8.tar.gz
          cd construct-2.8.8
          python3 setup.py bdist_wheel
          
          # 5. Copy the wheel to the correct absolute path
          mkdir -p $DIST_PATH/wheels
          cp dist/*.whl $DIST_PATH/wheels/
          
          # 6. Return to root and fix permissions
          cd ../../
          find $DIST_PATH -type d -print0 | xargs -0 chmod 755
          find $DIST_PATH -type f -print0 | xargs -0 chmod 644
          
          # VERIFICATION
          echo "Check if wheels folder exists:"
          ls -R $DIST_PATH/wheels

      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4