name: deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Build and publish to GitHub pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    concurrency:
      group: "pages"
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install protoc compiler
        run: |
          sudo apt-get update
          sudo apt-get install protobuf-compiler

      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      - uses: taiki-e/install-action@v2
        with:
          tool: zola

      - name: Build bundle
        run: |
          rm -rf dist/
          # 1. Build the Zola site into the dist folder
          (cd www-zola && zola build --output-dir ../dist)
          
          # 2. Build the Rust WASM package
          wasm-pack build --release --target web
          
          # 3. Copy WASM files into the deployment folder
          cp -r pkg dist/
          
          # 4. Fix permissions for GitHub servers
          find dist -type d -print0 | xargs -0 chmod 755
          find dist -type f -print0 | xargs -0 chmod 644

      - uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4